from .action import ActionAdmin
from .blood_pressure_data import BloodPressureDataAdmin
from .course import CourseAdmin
from .course_medicine import CourseMedicineAdmin
from .measurement import MeasurementAdmin
from .pulse_data import PulseDataAdmin
from .reminder import ReminderAdmin
from .steps_data import StepsDataAdmin
from .user import CustomUserAdmin
from .user_health_data import HealthDataAdmin
