# Generated by Django 5.2.4 on 2025-07-28 20:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                (
                    'is_superuser',
                    models.BooleanField(
                        default=False,
                        help_text='Designates that this user has all permissions without explicitly assigning them.',
                        verbose_name='superuser status',
                    ),
                ),
                (
                    'username',
                    models.CharField(
                        error_messages={'unique': 'A user with that username already exists.'},
                        help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name='username',
                    ),
                ),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                (
                    'is_staff',
                    models.BooleanField(
                        default=False,
                        help_text='Designates whether the user can log into this admin site.',
                        verbose_name='staff status',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                        verbose_name='active',
                    ),
                ),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('subscribe', models.BooleanField(default=False)),
                ('is_logged_in', models.BooleanField(default=False)),
                (
                    'groups',
                    models.ManyToManyField(
                        blank=True,
                        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.group',
                        verbose_name='groups',
                    ),
                ),
                (
                    'user_permissions',
                    models.ManyToManyField(
                        blank=True,
                        help_text='Specific permissions for this user.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.permission',
                        verbose_name='user permissions',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Юзер',
                'verbose_name_plural': 'Юзеры',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BloodPressureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('systolic', models.IntegerField()),
                ('diastolic', models.IntegerField()),
                ('pulse', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Данные кровеносного давления',
                'verbose_name_plural': 'Данные кровеносного давления',
                'db_table': 'blood_pressure_data',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Курс лечения',
                'verbose_name_plural': 'Курсы лечения',
                'db_table': 'courses_table',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_lifelong', models.BooleanField(default=False)),
                ('time', models.TimeField(blank=True, null=True)),
                ('action_type', models.CharField(default='action', max_length=20)),
                ('select_time', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                (
                    'schedule_type',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('interval', 'По интервалу'),
                            ('weekly', 'Еженедельно'),
                            ('cyclic', 'Циклически'),
                            ('single', 'Однократно'),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ('interval_value', models.IntegerField(blank=True, null=True)),
                (
                    'interval_unit',
                    models.CharField(
                        blank=True,
                        choices=[('days', 'Дни'), ('weeks', 'Недели'), ('months', 'Месяцы')],
                        max_length=10,
                        null=True,
                    ),
                ),
                ('selected_days_mask', models.IntegerField(default=0)),
                ('cycle_duration', models.IntegerField(blank=True, null=True)),
                ('cycle_break', models.IntegerField(blank=True, null=True)),
                ('cycle_break_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('notification', models.CharField(blank=True, max_length=255, null=True)),
                ('is_completed', models.BooleanField(blank=True, null=True)),
                ('times', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    'course',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course'
                    ),
                ),
            ],
            options={
                'db_table': 'actions_table',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_lifelong', models.BooleanField(default=False)),
                ('time', models.TimeField(blank=True, null=True)),
                ('select_time', models.CharField(blank=True, max_length=50, null=True)),
                ('measurement_type', models.CharField(default='measurement', max_length=20)),
                (
                    'schedule_type',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('interval', 'По интервалу'),
                            ('weekly', 'Еженедельно'),
                            ('cyclic', 'Циклически'),
                            ('single', 'Однократно'),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ('interval_value', models.IntegerField(blank=True, null=True)),
                (
                    'interval_unit',
                    models.CharField(
                        blank=True,
                        choices=[('days', 'Дни'), ('weeks', 'Недели'), ('months', 'Месяцы')],
                        max_length=10,
                        null=True,
                    ),
                ),
                ('selected_days_mask', models.IntegerField(default=0)),
                ('cycle_duration', models.IntegerField(blank=True, null=True)),
                ('cycle_break', models.IntegerField(blank=True, null=True)),
                ('cycle_break_unit', models.CharField(blank=True, max_length=10, null=True)),
                (
                    'course',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course'
                    ),
                ),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Регулярное измерение',
                'verbose_name_plural': 'Регулярные измерения',
                'db_table': 'measurements_table',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('release_form', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_in_package', models.CharField(blank=True, max_length=100, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('package_count', models.IntegerField(default=0)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лекарство',
                'verbose_name_plural': 'Лекарства',
                'db_table': 'medicines_table',
            },
        ),
        migrations.CreateModel(
            name='CourseMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicine')),
            ],
            options={
                'verbose_name': 'Лекарство в курсе',
                'verbose_name_plural': 'Лекарства в курсе',
                'db_table': 'course_medicines',
            },
        ),
        migrations.CreateModel(
            name='PulseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('systolic', models.IntegerField(blank=True, null=True)),
                ('diastolic', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Данные пульса',
                'verbose_name_plural': 'Данные пульса',
                'db_table': 'pulse_data',
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('select_time', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_lifelong', models.BooleanField(default=False)),
                (
                    'schedule_type',
                    models.CharField(
                        choices=[
                            ('interval', 'По интервалу'),
                            ('weekly', 'Еженедельно'),
                            ('cyclic', 'Циклически'),
                            ('single', 'Однократно'),
                        ],
                        max_length=20,
                    ),
                ),
                ('interval_value', models.IntegerField(blank=True, null=True)),
                (
                    'interval_unit',
                    models.CharField(
                        blank=True,
                        choices=[('days', 'Дни'), ('weeks', 'Недели'), ('months', 'Месяцы')],
                        max_length=10,
                        null=True,
                    ),
                ),
                ('selected_days_mask', models.IntegerField(default=0)),
                ('cycle_duration', models.IntegerField(blank=True, null=True)),
                ('cycle_break', models.IntegerField(blank=True, null=True)),
                ('cycle_break_unit', models.CharField(blank=True, max_length=10, null=True)),
                (
                    'reminder_type',
                    models.CharField(
                        choices=[('tablet', 'Лекарство'), ('action', 'Действие'), ('measurement', 'Измерение')],
                        default='tablet',
                        max_length=20,
                    ),
                ),
                ('is_completed', models.BooleanField(blank=True, null=True)),
                (
                    'course',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course'
                    ),
                ),
                (
                    'medicine',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.medicine'
                    ),
                ),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
                'db_table': 'reminders_table',
            },
        ),
        migrations.CreateModel(
            name='ReminderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_completed', models.BooleanField()),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reminder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статус напоминания',
                'verbose_name_plural': 'Статусы напоминаний',
                'db_table': 'reminder_statuses',
            },
        ),
        migrations.CreateModel(
            name='StepsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Данные шагов',
                'verbose_name_plural': 'Данные шагов',
                'db_table': 'steps_data',
            },
        ),
        migrations.CreateModel(
            name='UserHealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.CharField(blank=True, max_length=255, null=True)),
                ('heart_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Данные здоровья',
                'verbose_name_plural': 'Данные здоровья',
                'db_table': 'user_health_data',
            },
        ),
    ]
