# Generated by Django 5.2.4 on 2025-07-29 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(default='action', max_length=20, verbose_name='Тип действия'),
        ),
        migrations.AlterField(
            model_name='action',
            name='course',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='app.course',
                verbose_name='Связанный курс',
            ),
        ),
        migrations.AlterField(
            model_name='action',
            name='cycle_break',
            field=models.IntegerField(blank=True, null=True, verbose_name='Перерыв между циклами'),
        ),
        migrations.AlterField(
            model_name='action',
            name='cycle_break_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Единица измерения перерыва'),
        ),
        migrations.AlterField(
            model_name='action',
            name='cycle_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длительность цикла'),
        ),
        migrations.AlterField(
            model_name='action',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='action',
            name='interval_unit',
            field=models.CharField(
                blank=True,
                choices=[('days', 'Дни'), ('weeks', 'Недели'), ('months', 'Месяцы')],
                max_length=10,
                null=True,
                verbose_name='Единица измерения интервала',
            ),
        ),
        migrations.AlterField(
            model_name='action',
            name='interval_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Значение интервала'),
        ),
        migrations.AlterField(
            model_name='action',
            name='is_completed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='action',
            name='is_lifelong',
            field=models.BooleanField(default=False, verbose_name='Пожизненное действие'),
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='action',
            name='notification',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Уведомление'),
        ),
        migrations.AlterField(
            model_name='action',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='action',
            name='schedule_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('interval', 'По интервалу'),
                    ('weekly', 'Еженедельно'),
                    ('cyclic', 'Циклически'),
                    ('single', 'Однократно'),
                ],
                max_length=20,
                null=True,
                verbose_name='Тип расписания',
            ),
        ),
        migrations.AlterField(
            model_name='action',
            name='select_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Выбранное время'),
        ),
        migrations.AlterField(
            model_name='action',
            name='selected_days_mask',
            field=models.IntegerField(default=0, verbose_name='Маска выбранных дней'),
        ),
        migrations.AlterField(
            model_name='action',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='action',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время выполнения'),
        ),
        migrations.AlterField(
            model_name='action',
            name='times',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Времена выполнения'),
        ),
        migrations.AlterField(
            model_name='action',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'
            ),
        ),
        migrations.AlterField(
            model_name='bloodpressuredata',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='bloodpressuredata',
            name='date',
            field=models.DateTimeField(verbose_name='Дата и время измерения'),
        ),
        migrations.AlterField(
            model_name='bloodpressuredata',
            name='diastolic',
            field=models.IntegerField(
                help_text='Нижнее значение артериального давления', verbose_name='Диастолическое давление'
            ),
        ),
        migrations.AlterField(
            model_name='bloodpressuredata',
            name='pulse',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пульс'),
        ),
        migrations.AlterField(
            model_name='bloodpressuredata',
            name='systolic',
            field=models.IntegerField(
                help_text='Верхнее значение артериального давления', verbose_name='Систолическое давление'
            ),
        ),
        migrations.AlterField(
            model_name='bloodpressuredata',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'
            ),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'
            ),
        ),
        migrations.AlterField(
            model_name='coursemedicine',
            name='course',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='app.course', verbose_name='Курс лечения'
            ),
        ),
        migrations.AlterField(
            model_name='coursemedicine',
            name='dosage',
            field=models.CharField(max_length=100, verbose_name='Дозировка'),
        ),
        migrations.AlterField(
            model_name='coursemedicine',
            name='medicine',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='app.medicine', verbose_name='Лекарство'
            ),
        ),
        migrations.AlterField(
            model_name='coursemedicine',
            name='unit',
            field=models.CharField(max_length=50, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='coursemedicine',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'
            ),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='course',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='app.course',
                verbose_name='Связанный курс',
            ),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='cycle_break',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длительность перерыва'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='cycle_break_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Единица перерыва'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='cycle_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длительность цикла'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='interval_unit',
            field=models.CharField(
                blank=True,
                choices=[('days', 'Дни'), ('weeks', 'Недели'), ('months', 'Месяцы')],
                max_length=10,
                null=True,
                verbose_name='Единица интервала',
            ),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='interval_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Значение интервала'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='is_lifelong',
            field=models.BooleanField(default=False, verbose_name='Постоянное измерение'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='measurement_type',
            field=models.CharField(default='measurement', max_length=20, verbose_name='Тип измерения'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название измерения'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='schedule_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('interval', 'По интервалу'),
                    ('weekly', 'Еженедельно'),
                    ('cyclic', 'Циклически'),
                    ('single', 'Однократно'),
                ],
                max_length=20,
                null=True,
                verbose_name='Тип расписания',
            ),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='select_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Выбранное время'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='selected_days_mask',
            field=models.IntegerField(default=0, verbose_name='Маска выбранных дней'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время измерения'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'
            ),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к изображению'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название лекарства'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='package_count',
            field=models.IntegerField(default=0, verbose_name='Количество упаковок'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity_in_package',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Количество в упаковке'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='release_form',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Форма выпуска'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'
            ),
        ),
        migrations.AlterField(
            model_name='pulsedata',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='pulsedata',
            name='date',
            field=models.DateTimeField(verbose_name='Дата и время измерения'),
        ),
        migrations.AlterField(
            model_name='pulsedata',
            name='diastolic',
            field=models.IntegerField(blank=True, null=True, verbose_name='Диастолическое давление'),
        ),
        migrations.AlterField(
            model_name='pulsedata',
            name='systolic',
            field=models.IntegerField(blank=True, null=True, verbose_name='Систолическое давление'),
        ),
        migrations.AlterField(
            model_name='pulsedata',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'
            ),
        ),
        migrations.AlterField(
            model_name='pulsedata',
            name='value',
            field=models.IntegerField(verbose_name='Значение пульса'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='course',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='app.course',
                verbose_name='Связанный курс',
            ),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='cycle_break',
            field=models.IntegerField(blank=True, null=True, verbose_name='Перерыв между циклами'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='cycle_break_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Единица перерыва'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='cycle_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длительность цикла'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дозировка'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='interval_unit',
            field=models.CharField(
                blank=True,
                choices=[('days', 'Дни'), ('weeks', 'Недели'), ('months', 'Месяцы')],
                max_length=10,
                null=True,
                verbose_name='Единица интервала',
            ),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='interval_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Значение интервала'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='is_completed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='is_lifelong',
            field=models.BooleanField(default=False, verbose_name='Бессрочное'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='medicine',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='app.medicine',
                verbose_name='Связанное лекарство',
            ),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название напоминания'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(
                choices=[('tablet', 'Лекарство'), ('action', 'Действие'), ('measurement', 'Измерение')],
                default='tablet',
                max_length=20,
                verbose_name='Тип напоминания',
            ),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='schedule_type',
            field=models.CharField(
                choices=[
                    ('interval', 'По интервалу'),
                    ('weekly', 'Еженедельно'),
                    ('cyclic', 'Циклически'),
                    ('single', 'Однократно'),
                ],
                max_length=20,
                verbose_name='Тип расписания',
            ),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='select_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Выбранное время'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='selected_days_mask',
            field=models.IntegerField(default=0, verbose_name='Выбранные дни (маска)'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.TimeField(verbose_name='Время срабатывания'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'
            ),
        ),
        migrations.AlterField(
            model_name='reminderstatus',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='reminderstatus',
            name='is_completed',
            field=models.BooleanField(verbose_name='Закончен'),
        ),
        migrations.AlterField(
            model_name='reminderstatus',
            name='reminder',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='app.reminder', verbose_name='Напоминание'
            ),
        ),
        migrations.AlterField(
            model_name='reminderstatus',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'
            ),
        ),
        migrations.AlterField(
            model_name='stepsdata',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='stepsdata',
            name='count',
            field=models.IntegerField(verbose_name='Количество шагов'),
        ),
        migrations.AlterField(
            model_name='stepsdata',
            name='date',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='stepsdata',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_logged_in',
            field=models.BooleanField(default=False, verbose_name='Залогинен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribe',
            field=models.BooleanField(default=False, verbose_name='Подписка'),
        ),
        migrations.AlterField(
            model_name='userhealthdata',
            name='heart_rate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пульс'),
        ),
        migrations.AlterField(
            model_name='userhealthdata',
            name='steps',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество шагов'),
        ),
        migrations.AlterField(
            model_name='userhealthdata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='userhealthdata',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'
            ),
        ),
    ]
