# Generated by Django 5.2.4 on 2025-07-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0002_alter_action_options_alter_action_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='фамилия'),
        ),
    ]
