# Generated by Django 5.2.4 on 2025-08-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0003_user_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='package_count',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='user',
        ),
        migrations.AddField(
            model_name='medicine',
            name='active_ingredients',
            field=models.TextField(blank=True, null=True, verbose_name='Активные ингредиенты'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='barcodes',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Штрих-коды'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='composition',
            field=models.TextField(blank=True, null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='contraindications',
            field=models.TextField(blank=True, null=True, verbose_name='Противопоказания'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='drugs_interaction',
            field=models.TextField(blank=True, null=True, verbose_name='Взаимодействие с другими препаратами'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='indications',
            field=models.TextField(blank=True, null=True, verbose_name='Показания'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='manufacturer',
            field=models.TextField(blank=True, null=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='method_application_dosage',
            field=models.TextField(blank=True, null=True, verbose_name='Способ применения и дозы'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='origin_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна происхождения'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='overdose',
            field=models.TextField(blank=True, null=True, verbose_name='Передозировка'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='pharmacokinetics',
            field=models.TextField(blank=True, null=True, verbose_name='Фармакокинетика'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='pharmacological_effect',
            field=models.TextField(blank=True, null=True, verbose_name='Фармакологическое действие'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='pregnancy_usage',
            field=models.TextField(blank=True, null=True, verbose_name='Применение при беременности'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='safety_precautions',
            field=models.TextField(blank=True, null=True, verbose_name='Меры предосторожности'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='side_effects',
            field=models.TextField(blank=True, null=True, verbose_name='Побочные эффекты'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='special_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Особые указания'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='storage_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Условия хранения'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='vacation_procedure',
            field=models.TextField(blank=True, null=True, verbose_name='Порядок отпуска'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Название лекарства'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity_in_package',
            field=models.TextField(blank=True, null=True, verbose_name='Количество в упаковке'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='release_form',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма выпуска'),
        ),
    ]
