# Generated by Django 5.2.4 on 2025-08-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0004_remove_medicine_package_count_remove_medicine_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='active_ingredients',
            field=models.TextField(
                blank=True, db_column='ActiveIngredients', null=True, verbose_name='Активные ингредиенты'
            ),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='barcodes',
            field=models.BigIntegerField(blank=True, db_column='Barcodes', null=True, verbose_name='Штрих-коды'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='composition',
            field=models.TextField(blank=True, db_column='Composition', null=True, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='contraindications',
            field=models.TextField(
                blank=True, db_column='Contraindications', null=True, verbose_name='Противопоказания'
            ),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, db_column='Description', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='drugs_interaction',
            field=models.TextField(
                blank=True, db_column='DrugsInteraction', null=True, verbose_name='Взаимодействие с другими препаратами'
            ),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='image_path',
            field=models.CharField(
                blank=True, db_column='ImagePath', max_length=255, null=True, verbose_name='Путь к изображению'
            ),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='indications',
            field=models.TextField(blank=True, db_column='Indications', null=True, verbose_name='Показания'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufacturer',
            field=models.TextField(blank=True, db_column='Manufacturer', null=True, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='method_application_dosage',
            field=models.TextField(
                blank=True, db_column='MethodApplicationDosage', null=True, verbose_name='Способ применения и дозы'
            ),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.TextField(blank=True, db_column='Name', null=True, verbose_name='Название лекарства'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='origin_country',
            field=models.CharField(
                blank=True, db_column='OriginCountry', max_length=255, null=True, verbose_name='Страна происхождения'
            ),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='overdose',
            field=models.TextField(blank=True, db_column='Overdose', null=True, verbose_name='Передозировка'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='pharmacokinetics',
            field=models.TextField(blank=True, db_column='Pharmacokinetics', null=True, verbose_name='Фармакокинетика'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='pharmacological_effect',
            field=models.TextField(
                blank=True, db_column='PharmacologicalEffect', null=True, verbose_name='Фармакологическое действие'
            ),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='pregnancy_usage',
            field=models.TextField(
                blank=True, db_column='PregnancyUsage', null=True, verbose_name='Применение при беременности'
            ),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity_in_package',
            field=models.TextField(
                blank=True, db_column='QuantityInPackage', null=True, verbose_name='Количество в упаковке'
            ),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='release_form',
            field=models.CharField(
                blank=True, db_column='ReleaseForm', max_length=255, null=True, verbose_name='Форма выпуска'
            ),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='safety_precautions',
            field=models.TextField(
                blank=True, db_column='SafetyPrecautions', null=True, verbose_name='Меры предосторожности'
            ),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='side_effects',
            field=models.TextField(blank=True, db_column='SideEffects', null=True, verbose_name='Побочные эффекты'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='special_instructions',
            field=models.TextField(
                blank=True, db_column='SpecialInstructions', null=True, verbose_name='Особые указания'
            ),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='storage_conditions',
            field=models.TextField(
                blank=True, db_column='StorageConditions', null=True, verbose_name='Условия хранения'
            ),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='vacation_procedure',
            field=models.TextField(
                blank=True, db_column='VacationProcedure', null=True, verbose_name='Порядок отпуска'
            ),
        ),
        migrations.AlterModelTable(
            name='medicine',
            table='Medicines',
        ),
    ]
