# Generated by Django 5.2.4 on 2025-08-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0005_alter_medicine_active_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='barcodes',
            field=models.TextField(blank=True, db_column='Barcodes', null=True, verbose_name='Штрих-коды'),
        ),
    ]
