# Generated by Django 5.2.4 on 2025-08-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_medicine_barcodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='image_path',
            field=models.TextField(blank=True, db_column='ImagePath', max_length=255, null=True, verbose_name='Путь к изображению'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='origin_country',
            field=models.TextField(blank=True, db_column='OriginCountry', max_length=255, null=True, verbose_name='Страна происхождения'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='release_form',
            field=models.TextField(blank=True, db_column='ReleaseForm', max_length=255, null=True, verbose_name='Форма выпуска'),
        ),
    ]
